# Generated by Django 5.0.7 on 2024-09-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurcars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
        migrations.AddField(
            model_name='booking',
            name='test_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
