# Generated by Django 5.0.7 on 2024-09-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurcars', '0002_remove_car_available_booking_test_drive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='test_drive',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
