# Generated by Django 5.0.7 on 2024-09-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurcars', '0004_car_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_available',
            new_name='available',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
