# Generated by Django 5.0.7 on 2024-10-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurcars', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('test_drive_date', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futurcars.car')),
            ],
        ),
    ]
