# Generated by Django 5.0.7 on 2024-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurcars', '0008_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Booked', max_length=100),
        ),
        migrations.DeleteModel(
            name='TestDrive',
        ),
    ]
