# Generated by Django 5.0.7 on 2024-11-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurcars', '0009_booking_customer_email_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
